### ISSUE TITLE
Instructor Feedback Week 4 and 5 exercises

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [avmarks/Calorie-Manager#1]
I like your happy commit messages when things are working!

- [x] Consider overriding the .equals() method in each entity to make assertions easier in the tests (there's a video on this)
- [x] Is this needed?  https://github.com/avmarks/Calorie-Manager/blob/c0bfdef5072ca5a6ac7b1537d31327b52199aa80/src/main/java/edu/matc/persistence/FoodDAO.java#L35 getByPropertyEqual and getByPropertyLike should be enough?
- [x] Looks like you are in a good position to start implementing the generic dao, which will allow you to get rid of the User and Food dao AND you won't have to write any new Daos either!
- [x] Did you mention a concern about code coverage? What percent code coverage do you have in  your two Daos?

**Comment by avmarks** [comment]
Thank you for the feedback, all the issues have been addressed.
