### ISSUE TITLE
Rest Exercise Feedback

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [avmarks/Calorie-Manager#5]
- [x] Remember the restful naming best practices. users would be best here. https://github.com/avmarks/Calorie-Manager/blob/c1147370df0c1323afc32b910f5ab2181372f81b/src/main/java/edu/matc/controller/RESTfulWebController.java#L23
- [ ] I didn't see your application class? Are you able to access the service from a browser?

**Comment by avmarks** [comment]
Changed the naming. I'm able to see the result in the browser without access service. Does it mean that would not work when deployed to AWS?
![image](https://user-images.githubusercontent.com/24462868/38340487-614f365e-3839-11e8-90f5-98bbfd6b37fa.png)
